<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_in all topics and posts</name>
   <tag></tag>
   <elementGuidId>2bbfe4ce-a6be-4038-8038-5dbe33f28382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ember12']/div/div/div[2]/ul/li/a/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.label-suffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bab3ef21-6d7a-458e-bd44-297012b42be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-suffix</value>
      <webElementGuid>ffa2e472-e391-42c7-90b3-56b2de2b6036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>in all topics and posts</value>
      <webElementGuid>0d01cab0-c76c-400f-b860-db1dc1a98429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember12&quot;)/div[@class=&quot;search-widget&quot;]/div[@class=&quot;search-menu&quot;]/div[@class=&quot;results&quot;]/ul[@class=&quot;search-menu-initial-options&quot;]/li[@class=&quot;search-menu-assistant-item&quot;]/a[@class=&quot;widget-link search-link&quot;]/span[@class=&quot;search-item-slug&quot;]/span[@class=&quot;label-suffix&quot;]</value>
      <webElementGuid>050e06c6-2add-404f-b44f-099b0dd822fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember12']/div/div/div[2]/ul/li/a/span/span[2]</value>
      <webElementGuid>15473da3-e505-43bb-ab09-82b3d15f7c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chrome'])[1]/following::span[1]</value>
      <webElementGuid>1fb26352-4606-40e7-941f-03234ab3e7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Katalon Community!'])[1]/following::span[3]</value>
      <webElementGuid>337e0afe-9b88-40d6-8644-e7dece10a620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or press Enter'])[1]/preceding::span[1]</value>
      <webElementGuid>1563b007-0813-4d15-b1c6-ad07741cab1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chrome'])[1]/preceding::span[2]</value>
      <webElementGuid>139f8333-6d20-45b8-a743-d353b184a047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='in all topics and posts']/parent::*</value>
      <webElementGuid>c0cbf78f-5939-4931-9d37-b739c8885787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>8c06459f-7962-48a8-9cdc-8315e3c76644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'in all topics and posts' or . = 'in all topics and posts')]</value>
      <webElementGuid>a56a8a07-bb4f-40a7-816f-bcd9317c5c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
